spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/shippingdb}
    username: ${SPRING_DATASOURCE_USERNAME:shipping}
    password: ${SPRING_DATASOURCE_PASSWORD:shipping}