spring:
  application:
    name: customer-service

  datasource:
      url: jdbc:postgresql://localhost:5432/customerdb
      username: customer
      password: customer

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: 7z4rA5L9kP2xQ8mN6vT1sW3yB8cD4eF7hJ9mN2pQ5rS8tV1xY4zA6cE9gH2jK5m
  expiration: 3600000  