spring:
  application:
    name: customer-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/customerdb}
    username: ${DB_USERNAME:customer}
    password: ${DB_PASSWORD:customer}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true


server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}