spring:
  application:
    name: auth-service

customer-service:
  base-url: http://customer-service:8080


server:
  port: ${SERVER_PORT:8085}

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXphYmNkZWZnaGlqa2xtbm9wcQ==
  expiration: 3600000
