spring:
  application:
    name: authentication-service

customer-service:
  base-url: http://customer-service:8080


server:
  port: ${SERVER_PORT:8085}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}


