spring:
  application:
    name: order-service

  datasource:
      url: jdbc:postgresql://localhost:5434/orderdb
      username: order
      password: order

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8082}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000} 

services:
  customer:
    base-url: ${CUSTOMER_SERVICE_URL:http://localhost:8081}

  product:
    base-url: ${PRODUCT_SERVICE_URL:http://localhost:8083}

  inventory:
    base-url: ${INVENTORY_SERVICE_URL:http://localhost:8084}  


