spring:
  application:
    name: order-service

  datasource:
      url: jdbc:postgresql://localhost:5434/orderdb
      username: order
      password: order

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

    

server:
    port: 8082

services:
  customer:
    base-url: http://localhost:8081

  product:
    base-url: http://localhost:8083

 

