spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/productdb}
    username: ${SPRING_DATASOURCE_USERNAME:product}
    password: ${SPRING_DATASOURCE_PASSWORD:product}